### ISSUE TITLE
Post block broken

### ISSUE THREAD

**Issue by universpharmacie** [maximebj/advanced-gutenberg-blocks#15] opened 2018-10-25 10:18 UTC
Can be created in the back end, renders well in the front end, but when returning to the back end, the info about the linked post gets lost :

https://wordpress.org/support/topic/post-block-again-broken-with-gutenberg-4-0/

**Comment by maximebj** [comment] 2018-12-06 10:00
Hi, 
The issue is fixed in the today new release !

Thank you !

**Closed by maximebj** 2018-12-06 10:00 UTC
